### PR TITLE
Refactor yelp example

### PR DESCRIPTION
**Pull request by ryanjduffy**
Adopts new helper functions in yelp example and refactors source to be more readable / reusable.

https://replay.io/view?id=d853e5fa-400c-40ae-9584-15a1329bad72

Blocked by #29

### CODE REVIEW

**Review by jasonLaster — APPROVED** [review]
Looks great!

**Comment by jasonLaster** [comment]
feel free to land when the conflicts are resolved

**Comment by ryanjduffy** [comment]
Resolved!

**Comment by jasonLaster** [comment]
Merge away

**Pull request merged**
